version: '3'
services:
  my-zookeeper:
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"
  my-kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.100
      KAFKA_ZOOKEEPER_CONNECT: my-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock